<?php

namespace ContainerKRTlGUM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SV5jjPKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SV5jjPK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SV5jjPK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.FNL2vdj', 'get_ServiceLocator_FNL2vdjService', true],
            'App\\Controller\\LogementController::deleteLogement' => ['privates', '.service_locator.kt2H8I.', 'get_ServiceLocator_Kt2H8I_Service', true],
            'App\\Controller\\LogementController::index' => ['privates', '.service_locator.kt2H8I.', 'get_ServiceLocator_Kt2H8I_Service', true],
            'App\\Controller\\LogementController::updatelogement' => ['privates', '.service_locator.kt2H8I.', 'get_ServiceLocator_Kt2H8I_Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.b.io7Lr', 'get_ServiceLocator_B_Io7LrService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::deleteUser' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController::updateUser' => ['privates', '.service_locator.hY_Trkc', 'get_ServiceLocator_HYTrkcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.FNL2vdj', 'get_ServiceLocator_FNL2vdjService', true],
            'App\\Controller\\LogementController:deleteLogement' => ['privates', '.service_locator.kt2H8I.', 'get_ServiceLocator_Kt2H8I_Service', true],
            'App\\Controller\\LogementController:index' => ['privates', '.service_locator.kt2H8I.', 'get_ServiceLocator_Kt2H8I_Service', true],
            'App\\Controller\\LogementController:updatelogement' => ['privates', '.service_locator.kt2H8I.', 'get_ServiceLocator_Kt2H8I_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.b.io7Lr', 'get_ServiceLocator_B_Io7LrService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:deleteUser' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController:updateUser' => ['privates', '.service_locator.hY_Trkc', 'get_ServiceLocator_HYTrkcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\LogementController::deleteLogement' => '?',
            'App\\Controller\\LogementController::index' => '?',
            'App\\Controller\\LogementController::updatelogement' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::deleteUser' => '?',
            'App\\Controller\\UserController::updateUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\LogementController:deleteLogement' => '?',
            'App\\Controller\\LogementController:index' => '?',
            'App\\Controller\\LogementController:updatelogement' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:deleteUser' => '?',
            'App\\Controller\\UserController:updateUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
