<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZdEExy4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZdEExy4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZdEExy4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZdEExy4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZdEExy4\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZdEExy4',
    'container.build_id' => 'a3a6d9e0',
    'container.build_time' => 1613658619,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZdEExy4');
