<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVuGOc6E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVuGOc6E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVuGOc6E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVuGOc6E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVuGOc6E\App_KernelDevDebugContainer([
    'container.build_hash' => 'VuGOc6E',
    'container.build_id' => '8e3e056f',
    'container.build_time' => 1613743004,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVuGOc6E');
