<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNjIR7Tg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNjIR7Tg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNjIR7Tg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNjIR7Tg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNjIR7Tg\App_KernelDevDebugContainer([
    'container.build_hash' => 'NjIR7Tg',
    'container.build_id' => '5f52824d',
    'container.build_time' => 1613835293,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNjIR7Tg');
